/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Brazo;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import static java.awt.image.ImageObserver.ERROR;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alisonfernandez
 */
public class Frame_Brazo extends javax.swing.JFrame {

    private static final String b_inicio = "0";
    private static final String b_abortar = "1";
    private static String cadena = "";
    
    private OutputStream output = null;
    SerialPort serialPort;
    private final String PUERTO = "/dev/cu.usbmodem1411";
    
    private static final int TIMEOUT = 2000;
    private static final int DATA_RATE = 9600;

    /**
     * Creates new form Frame_Brazo
     */
    public Frame_Brazo() {
        initComponents();
        inicializarConexion();
        setTitle("Brazo Robotco");
        imagenBrazo.setIcon(new ImageIcon("src/Imagenes/arm.jpg"));
    }

    public void inicializarConexion(){
        CommPortIdentifier puertoID=null;
        Enumeration puertoEnum=CommPortIdentifier.getPortIdentifiers();
        
        while(puertoEnum.hasMoreElements()){
            CommPortIdentifier actualPuertoID=(CommPortIdentifier) puertoEnum.nextElement();
            if(PUERTO.equals(actualPuertoID.getName())){
                puertoID=actualPuertoID;
                break;
            }
        }
        
        if(puertoID==null){
            mostrarError("No se puede conectar al puerto");
            System.exit(ERROR);
        }
        
        try{
            serialPort = (SerialPort) puertoID.open(this.getClass().getName(), TIMEOUT);
            //Parámetros puerto serie
            
            serialPort.setSerialPortParams(DATA_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            
            output = serialPort.getOutputStream();
        } catch(Exception e){
            mostrarError(e.getMessage());
            System.exit(ERROR);
            
        }
    }
    
     private void enviarDatos(String datos){
        try{
            output.write(datos.getBytes());
            System.out.println(datos.getBytes());
        } catch(Exception e){
            mostrarError("ERROR");
            System.exit(ERROR);
        }
    }    
    
    public void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        imagenBrazo = new javax.swing.JLabel();
        iniciarB = new javax.swing.JButton();
        abortarB = new javax.swing.JButton();
        arla = new javax.swing.JLabel();
        fmaj = new javax.swing.JLabel();
        pasosB = new javax.swing.JTextField();
        enviarB = new javax.swing.JButton();
        instruccionesB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        titulo.setFont(new java.awt.Font("Zapfino", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 51));
        titulo.setText("Brazo Robotico de 4 DOF");

        imagenBrazo.setText("jLabel2");
        imagenBrazo.setPreferredSize(new java.awt.Dimension(640, 426));

        iniciarB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        iniciarB.setForeground(new java.awt.Color(0, 0, 51));
        iniciarB.setText("Iniciar");
        iniciarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBActionPerformed(evt);
            }
        });

        abortarB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        abortarB.setForeground(new java.awt.Color(0, 0, 51));
        abortarB.setText("Abortar");
        abortarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortarBActionPerformed(evt);
            }
        });

        arla.setText("Arvizu Ramirez Luis Alberto");

        fmaj.setText("Fernández Martínez Alison Joselyn");

        pasosB.setText("Ingresar pasos para manipular el brazo");
        pasosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasosBActionPerformed(evt);
            }
        });

        enviarB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        enviarB.setForeground(new java.awt.Color(0, 0, 51));
        enviarB.setText("Enviar");
        enviarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBActionPerformed(evt);
            }
        });

        instruccionesB.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        instruccionesB.setForeground(new java.awt.Color(0, 0, 51));
        instruccionesB.setText("Instrucciones");
        instruccionesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruccionesBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instruccionesB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arla)
                            .addComponent(fmaj))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(imagenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pasosB, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(enviarB)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iniciarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abortarB)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(imagenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarB)
                    .addComponent(abortarB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fmaj))
                    .addComponent(instruccionesB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abortarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortarBActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_abortar);
    }//GEN-LAST:event_abortarBActionPerformed

    private void iniciarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBActionPerformed
        // TODO add your handling code here:
        enviarDatos(b_inicio);
    }//GEN-LAST:event_iniciarBActionPerformed

    private void pasosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasosBActionPerformed
        // TODO add your handling code here:
        cadena = pasosB.getText();
    }//GEN-LAST:event_pasosBActionPerformed

    private void enviarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBActionPerformed
        // TODO add your handling code here:
        enviarDatos("x");
        for(int i=0, l=cadena.length(); i<l; i++ ){
            enviarDatos(String.valueOf(cadena.charAt(i)));
        }
    }//GEN-LAST:event_enviarBActionPerformed

    private void instruccionesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instruccionesBActionPerformed
        // TODO add your handling code here:
        new Instrucciones_Brazo(this, true);
    }//GEN-LAST:event_instruccionesBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Brazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Brazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Brazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Brazo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Brazo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortarB;
    private javax.swing.JLabel arla;
    private javax.swing.JButton enviarB;
    private javax.swing.JLabel fmaj;
    private javax.swing.JLabel imagenBrazo;
    private javax.swing.JButton iniciarB;
    private javax.swing.JButton instruccionesB;
    private javax.swing.JTextField pasosB;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
